;;; tree-edit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tree-edit.el

(register-definition-prefixes "tree-edit" '("tree-edit-"))


;;; Generated autoloads from tree-edit-build.el

(autoload 'tree-edit-install-language-grammar "tree-edit-build" "\
Compile grammar at PATH, and place the resulting shared library in DESTINATION.

(fn LANG)")
(autoload 'tree-edit-install-grammars-wizard "tree-edit-build" "\
Install all available tree-sitter grammars compatible with tree-edit.

FORCE-REBUILD, if non-nil or C-u prefix is used, forces a rebuild of the grammars even if cached.
ACCEPT-ALL, if non-nil, installs all grammars without confirmation.

(fn FORCE-REBUILD &optional ACCEPT-ALL)" t)
(register-definition-prefixes "tree-edit-build" '("tree-edit--"))


;;; Generated autoloads from tree-edit-python.el

(register-definition-prefixes "tree-edit-python" '("tree-edit-python-block-deletion-override"))

;;; End of scraped data

(provide 'tree-edit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tree-edit-autoloads.el ends here
