;;; reazon-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from reazon.el

(register-definition-prefixes "reazon" '("reazon-"))


;;; Generated autoloads from reazon-perf.el

(register-definition-prefixes "reazon-perf" '("reazon-"))


;;; Generated autoloads from reazon-sudoku.el

(register-definition-prefixes "reazon-sudoku" '("reazon-"))

;;; End of scraped data

(provide 'reazon-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; reazon-autoloads.el ends here
